name = "d1-worker"
main = "src/index.js"
compatibility_date = "2024-03-26"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "hoox-trading-db"
database_id = "48d7ba4f-49ce-426e-bc90-41ffba86658f" 

# Secrets to be added with wrangler:
# wrangler secret put INTERNAL_SERVICE_KEY 